server {

    listen 80 default_server;
    root /var/www/html;
    index index.html index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt { access_log off; log_not_found off; }

    access_log off;
    error_log /var/log/nginx/error.log error;

    sendfile off;

    client_max_body_size 100m;

    location ~ .php$ {
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        # Increase the timeout for processing long requests
        fastcgi_read_timeout 600;          # Increase read timeout to 600 seconds
        fastcgi_send_timeout 600;          # Increase send timeout to 600 seconds
        fastcgi_connect_timeout 600;       # Increase connection timeout to 600 seconds

        # Increase buffer size for larger responses
        fastcgi_buffer_size 32k;           # Increase buffer size to 32 KB
        fastcgi_buffers 8 32k;             # Increase buffer pool to 8 buffers, each 32 KB
        fastcgi_busy_buffers_size 64k;     # Adjust busy buffer size to 64 KB
        fastcgi_temp_file_write_size 128k; # Temporary file write size set to 128 KB

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
    }

    location ~ /.ht {
        deny all;
    }
}
